# Site settings
title: Insights at Workshop 14
email: i_have_a_cunning_plan@workshop14.io
description: > # this means to ignore newlines until "baseurl:"
  Work and insights from Crowdhailer at Workshop 14.
  I focus on developing lightweight solutions to modern standards.
  This blog will cover these, effecient workflow and other items of interest
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://insights.workshop14.io" # the base hostname & protocol for your site
twitter_username: CrowdHailer
github_username:  CrowdHailer

# Build settings
markdown: kramdown
